on:
  workflow_call:
    inputs: { }

jobs:
  test-nextjs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: |
            web-nextjs/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('web-nextjs/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web-nextjs/package-lock.json

      - name: Install dependencies
        run: |
          cd web-nextjs
          npm ci

      - name: Run tests
        run: |
          cd web-nextjs
          npm test
